/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIdRouteRouteImport } from './routes/app/$appId/route'
import { Route as AppAppIdIndexRouteImport } from './routes/app/$appId/index'
import { Route as AppAppIdTrainRouteImport } from './routes/app/$appId/train'
import { Route as AppAppIdResultsRouteImport } from './routes/app/$appId/results'
import { Route as AppAppIdDashboardRouteImport } from './routes/app/$appId/dashboard'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdRouteRoute = AppAppIdRouteRouteImport.update({
  id: '/app/$appId',
  path: '/app/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIdIndexRoute = AppAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppIdRouteRoute,
} as any)
const AppAppIdTrainRoute = AppAppIdTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AppAppIdRouteRoute,
} as any)
const AppAppIdResultsRoute = AppAppIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppAppIdRouteRoute,
} as any)
const AppAppIdDashboardRoute = AppAppIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAppIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/app/$appId': typeof AppAppIdRouteRouteWithChildren
  '/app/$appId/dashboard': typeof AppAppIdDashboardRoute
  '/app/$appId/results': typeof AppAppIdResultsRoute
  '/app/$appId/train': typeof AppAppIdTrainRoute
  '/app/$appId/': typeof AppAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/app/$appId/dashboard': typeof AppAppIdDashboardRoute
  '/app/$appId/results': typeof AppAppIdResultsRoute
  '/app/$appId/train': typeof AppAppIdTrainRoute
  '/app/$appId': typeof AppAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/app/$appId': typeof AppAppIdRouteRouteWithChildren
  '/app/$appId/dashboard': typeof AppAppIdDashboardRoute
  '/app/$appId/results': typeof AppAppIdResultsRoute
  '/app/$appId/train': typeof AppAppIdTrainRoute
  '/app/$appId/': typeof AppAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/app/$appId'
    | '/app/$appId/dashboard'
    | '/app/$appId/results'
    | '/app/$appId/train'
    | '/app/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/app/$appId/dashboard'
    | '/app/$appId/results'
    | '/app/$appId/train'
    | '/app/$appId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/app/$appId'
    | '/app/$appId/dashboard'
    | '/app/$appId/results'
    | '/app/$appId/train'
    | '/app/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AppAppIdRouteRoute: typeof AppAppIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId': {
      id: '/app/$appId'
      path: '/app/$appId'
      fullPath: '/app/$appId'
      preLoaderRoute: typeof AppAppIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$appId/': {
      id: '/app/$appId/'
      path: '/'
      fullPath: '/app/$appId/'
      preLoaderRoute: typeof AppAppIdIndexRouteImport
      parentRoute: typeof AppAppIdRouteRoute
    }
    '/app/$appId/train': {
      id: '/app/$appId/train'
      path: '/train'
      fullPath: '/app/$appId/train'
      preLoaderRoute: typeof AppAppIdTrainRouteImport
      parentRoute: typeof AppAppIdRouteRoute
    }
    '/app/$appId/results': {
      id: '/app/$appId/results'
      path: '/results'
      fullPath: '/app/$appId/results'
      preLoaderRoute: typeof AppAppIdResultsRouteImport
      parentRoute: typeof AppAppIdRouteRoute
    }
    '/app/$appId/dashboard': {
      id: '/app/$appId/dashboard'
      path: '/dashboard'
      fullPath: '/app/$appId/dashboard'
      preLoaderRoute: typeof AppAppIdDashboardRouteImport
      parentRoute: typeof AppAppIdRouteRoute
    }
  }
}

interface AppAppIdRouteRouteChildren {
  AppAppIdDashboardRoute: typeof AppAppIdDashboardRoute
  AppAppIdResultsRoute: typeof AppAppIdResultsRoute
  AppAppIdTrainRoute: typeof AppAppIdTrainRoute
  AppAppIdIndexRoute: typeof AppAppIdIndexRoute
}

const AppAppIdRouteRouteChildren: AppAppIdRouteRouteChildren = {
  AppAppIdDashboardRoute: AppAppIdDashboardRoute,
  AppAppIdResultsRoute: AppAppIdResultsRoute,
  AppAppIdTrainRoute: AppAppIdTrainRoute,
  AppAppIdIndexRoute: AppAppIdIndexRoute,
}

const AppAppIdRouteRouteWithChildren = AppAppIdRouteRoute._addFileChildren(
  AppAppIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AppAppIdRouteRoute: AppAppIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
